"""Contracts that make the reward optimizations safe to keep.

These are not timing tests. They pin the two things a fast path can silently
break: the numbers it produces, and how much work it does to produce them
(judge calls, context traversals). Every optimization in `reward.py` is
answerable to one of them.
"""

from __future__ import annotations

import json
import math
import random
from pathlib import Path

import sys

import pytest

pytest.importorskip("torch")

from src.agents.core.base import AgentLoopOutput  # noqa: E402
from src.context.search import AgentContext, SearchResult  # noqa: E402
from src.model.post_training.grpo.algorithms import (  # noqa: E402
    compute_grpo_outcome_advantage,
)
from dataclasses import replace  # noqa: E402

from src.model.post_training.reward import (  # noqa: E402
    SearchRewardConfig,
    SearchRewardFunction,
    grouped_relative_advantages,
    token_f1_score,
)

BASELINE_PATH = Path(__file__).with_name("reward_breakdown_baseline.json")

PRESETS = {
    "default": SearchRewardConfig(),
    "sparse_final_only": SearchRewardConfig.sparse_final_only(),
    "simple_sparse_with_search_penalty": (
        SearchRewardConfig.simple_sparse_with_search_penalty()
    ),
    "second_pass": SearchRewardConfig.second_pass(),
    "third_pass_with_format": SearchRewardConfig.third_pass_with_format(),
    "retriever_aware": SearchRewardConfig.retriever_aware(),
}


@pytest.fixture(scope="module")
def reward_baseline():
    """Breakdowns captured from the pre-optimization implementation.

    Provenance matters here and git cannot corroborate it: this file was
    generated by running `_write_baseline()` against `reward.py` as of 7265517
    — before any optimization — but it was committed alongside the change it
    polices (38ed3c2), which is exactly the failure mode a golden file exists to
    prevent. It is cross-checked two other ways: the differential oracles above
    pin the advantage kernels against the pre-refactor arithmetic directly, and
    `test_zeroed_dimensions_report_every_key_the_full_path_reports` compares the
    fast and full paths without consulting this file at all.

    To re-derive it from scratch rather than trusting it::

        git show 7265517:src/model/post_training/reward.py > /tmp/old_reward.py
        # ...and diff its reward_components output against the current one.

    Regenerating it is never the fix for a red test — a diff here means a
    breakdown changed, which this branch is not allowed to do::

        python -m tests.unit.test_reward_performance_contracts --write-baseline
    """
    data = json.loads(BASELINE_PATH.read_text())

    def lookup(preset_name: str, answer: str | None) -> dict:
        return data[preset_name][_answer_key(answer)]

    return lookup


def _answer_key(answer: str | None) -> str:
    return "<none>" if answer is None else (answer or "<empty>")


def _context() -> AgentContext:
    ctx = AgentContext()
    ctx.add_round(
        ["q1", "q2"],
        [
            [
                SearchResult(contents=f"doc {i}", url=f"https://example.test/a/{i}")
                for i in range(3)
            ],
            [
                SearchResult(contents=f"doc {i}", url=f"https://example.test/b/{i}")
                for i in range(3)
            ],
        ],
    )
    ctx.record_fetched_pages(
        [SearchResult(contents="p", url="https://example.test/a/0")]
    )
    return ctx


def _output(
    answer: str | None = "Vectors [R1Q1D1] and more [R1Q2D2].",
) -> AgentLoopOutput:
    return AgentLoopOutput(
        prompt_ids=[1, 2, 3],
        response_ids=list(range(8)),
        response_mask=[1] * 6 + [0, 0],
        num_turns=2,
        final_answer=answer,
        context=_context(),
        metrics={
            "rounds_used": 2.0,
            "search_rounds": 2.0,
            "repeated_search_queries": 1.0,
            "unnecessary_fetch_count": 1.0,
            "web_searches": 1.0,
            "vdb_searches": 1.0,
            "rerank_calls": 1.0,
            "search_quality_score": 0.5,
            "final_evidence_sufficient": 1.0,
            "subquestion_coverage_ratio": 0.75,
            "evidence_gain_total": 0.25,
            "early_stops": 1.0,
            "answer_allowed": 1.0,
        },
    )


# ---------------------------------------------------------------------------
# One canonical group-advantage kernel
# ---------------------------------------------------------------------------


def _pre_refactor_outcome_advantages(
    rewards: list[float], group_ids: list[str]
) -> list[float]:
    """`SearchRewardFunction.compute_grpo_outcome_advantages` as of 4abdf48.

    Kept inline as a differential oracle. Asserting that the wrapper equals the
    kernel proves only that one calls the other — both sides move together, so
    any change to the arithmetic stays green. This pins the arithmetic itself.
    """
    if len(rewards) != len(group_ids):
        raise ValueError("rewards and group_ids must have the same length.")
    groups: dict[str, list[tuple[int, float]]] = {}
    for idx, (gid, reward) in enumerate(zip(group_ids, rewards)):
        groups.setdefault(gid, []).append((idx, reward))
    advantages = [0.0] * len(rewards)
    for group in groups.values():
        if len(group) == 1:
            continue
        indices, group_rewards = zip(*group)
        mean = sum(group_rewards) / len(group_rewards)
        for idx, reward in zip(indices, group_rewards):
            advantages[idx] = reward - mean
    return advantages


def _pre_refactor_batch_advantages(
    rewards: list[float], group_ids: list[str]
) -> list[float]:
    """`SearchRewardFunction.compute_batch_advantages` as of 4abdf48.

    Note the `** 2`: this is the historical arithmetic, deliberately not the
    `c * c` the current kernel uses. See the one-ULP test below.
    """
    if len(rewards) != len(group_ids):
        raise ValueError("rewards and group_ids must have the same length.")
    groups: dict[str, list[tuple[int, float]]] = {}
    for idx, (gid, reward) in enumerate(zip(group_ids, rewards)):
        groups.setdefault(gid, []).append((idx, reward))
    advantages = [0.0] * len(rewards)
    for group in groups.values():
        if len(group) == 1:
            continue
        indices, group_rewards = zip(*group)
        n = len(group_rewards)
        mean = sum(group_rewards) / n
        variance = sum((r - mean) ** 2 for r in group_rewards) / n
        std = math.sqrt(variance)
        for idx, reward in zip(indices, group_rewards):
            advantages[idx] = (reward - mean) / (std + 1e-8)
    return advantages


def _random_groups(seed: int, count: int = 400):
    rng = random.Random(seed)
    for _ in range(count):
        size = rng.randint(1, 17)
        rewards = [rng.uniform(-3.0, 3.0) for _ in range(size)]
        group_ids = [f"g{rng.randint(0, 3)}" for _ in range(size)]
        yield rewards, group_ids


def test_outcome_advantages_are_bit_identical_to_the_pre_refactor_code():
    reward_fn = SearchRewardFunction()

    for rewards, group_ids in _random_groups(seed=1301):
        assert reward_fn.compute_grpo_outcome_advantages(rewards, group_ids) == (
            _pre_refactor_outcome_advantages(rewards, group_ids)
        )


def test_normalized_advantages_match_the_pre_refactor_code_to_one_ulp():
    """The normalized path is equal to within one unit in the last place.

    Not bit-identical, and the gap is not this branch's: #554's shared kernel
    squares the *pre-centered* values (`c * c`) where the code it replaced wrote
    `(r - mean) ** 2`. Those are mathematically the same, but CPython routes
    `** 2` through libm's `pow`, which is not always bit-equal to a multiply, so
    about 0.2% of random groups land one ULP apart. Asserting exact equality
    here would fail against `main` itself. The centering path above *is* exact,
    and is asserted as such.
    """
    reward_fn = SearchRewardFunction()

    for rewards, group_ids in _random_groups(seed=4507):
        actual = reward_fn.compute_batch_advantages(rewards, group_ids)
        expected = _pre_refactor_batch_advantages(rewards, group_ids)
        assert actual == pytest.approx(expected, rel=1e-12, abs=1e-15)


def test_the_kernel_uses_compensated_summation_like_the_code_it_replaced():
    """A hand-rolled `total += ...` mean is not `sum()` on CPython 3.12+.

    `sum()` applies Neumaier compensation over floats; a manual accumulator does
    not. This input is chosen so the two disagree, which is what makes swapping
    the builtin out a behavior change rather than a refactor.
    """
    values = [1e16, 1.0, -1e16, 1.0]
    naive = 0.0
    for value in values:
        naive += value
    if sys.version_info >= (3, 12):  # Neumaier compensation landed in 3.12
        assert naive != sum(values)

    actual = grouped_relative_advantages(values, ["g"] * 4, normalize=False)
    expected = [value - sum(values) / 4 for value in values]
    assert actual == expected


def test_outcome_advantages_delegate_to_the_canonical_kernel():
    rewards = [1.0, 0.4, 0.1, 0.9, 0.9]
    groups = ["a", "a", "a", "b", "b"]
    reward_fn = SearchRewardFunction()

    assert reward_fn.compute_grpo_outcome_advantages(rewards, groups) == (
        grouped_relative_advantages(rewards, groups, normalize=False)
    )


def test_normalized_advantages_delegate_to_the_canonical_kernel():
    rewards = [1.0, 0.4, 0.1, 0.9, 0.2]
    groups = ["a", "a", "a", "b", "b"]
    reward_fn = SearchRewardFunction()

    assert reward_fn.compute_batch_advantages(rewards, groups) == (
        grouped_relative_advantages(rewards, groups, normalize=True)
    )


def test_list_advantage_entry_point_delegates_to_the_canonical_kernel():
    rewards = [1.0, 0.4, 0.1]

    assert compute_grpo_outcome_advantage(rewards) == (
        grouped_relative_advantages(rewards, ["g"] * 3, normalize=False)
    )


@pytest.mark.parametrize("normalize", [False, True])
def test_singleton_groups_have_no_within_group_signal(normalize: bool):
    result = grouped_relative_advantages([3.0, -1.0], ["a", "b"], normalize=normalize)

    assert result == [0.0, 0.0]


@pytest.mark.parametrize("normalize", [False, True])
def test_zero_variance_groups_produce_zero_advantages(normalize: bool):
    result = grouped_relative_advantages(
        [0.5, 0.5, 0.5], ["a"] * 3, normalize=normalize
    )

    assert result == [0.0, 0.0, 0.0]


def test_groups_do_not_leak_into_one_another():
    interleaved = grouped_relative_advantages(
        [1.0, 10.0, 0.0, 20.0], ["a", "b", "a", "b"], normalize=False
    )

    assert interleaved == [0.5, -5.0, -0.5, 5.0]


def test_results_stay_in_input_order_not_group_order():
    result = grouped_relative_advantages(
        [0.0, 5.0, 1.0], ["b", "a", "b"], normalize=False
    )

    assert result == [-0.5, 0.0, 0.5]


def test_the_kernel_rejects_mismatched_lengths():
    with pytest.raises(ValueError, match="same length"):
        grouped_relative_advantages([1.0, 2.0], ["a"], normalize=False)


def test_the_kernel_handles_empty_input():
    assert grouped_relative_advantages([], [], normalize=True) == []


# ---------------------------------------------------------------------------
# Judge invocation counts
# ---------------------------------------------------------------------------


def test_reward_components_invokes_the_judge_exactly_once():
    calls: list[tuple[str, str]] = []

    def judge(answer: str, gold: str) -> float:
        calls.append((answer, gold))
        return 1.0

    SearchRewardFunction().reward_components(_output(), "gold", judge)

    assert len(calls) == 1


def test_batch_sparse_rewards_invoke_the_judge_once_per_answer():
    calls = 0

    def judge(answer: str, gold: str) -> float:
        nonlocal calls
        calls += 1
        return 1.0

    outputs = [_output() for _ in range(4)]
    SearchRewardFunction().compute_batch_sparse_token_rewards(
        outputs, ["gold"] * 4, judge
    )

    assert calls == 4


def test_batch_sparse_rewards_prefer_a_single_batch_judge_call():
    single_calls = 0
    batch_calls = 0

    def judge(answer: str, gold: str) -> float:
        nonlocal single_calls
        single_calls += 1
        return 0.0

    def batch_judge(answers: list[str], golds: list[str]) -> list[float]:
        nonlocal batch_calls
        batch_calls += 1
        return [1.0] * len(answers)

    outputs = [_output() for _ in range(4)]
    result = SearchRewardFunction().compute_batch_sparse_token_rewards(
        outputs, ["gold"] * 4, judge, batch_judge_fn=batch_judge
    )

    assert batch_calls == 1
    assert single_calls == 0
    assert [row[5] for row in result] == [1.0] * 4


def test_batch_length_is_validated_before_the_judge_is_invoked():
    def judge(answers, golds):  # pragma: no cover - must never run
        raise AssertionError("judge invoked on invalid input")

    with pytest.raises(ValueError, match="same length"):
        SearchRewardFunction().compute_batch_sparse_token_rewards(
            [_output()], ["gold", "extra"], judge, batch_judge_fn=judge
        )

    with pytest.raises(ValueError, match="same length"):
        SearchRewardFunction().assign_grpo_outcome_token_advantages(
            [_output()], ["gold", "extra"], judge, ["g"], batch_judge_fn=judge
        )


# ---------------------------------------------------------------------------
# Doing less work must not change any number
# ---------------------------------------------------------------------------


def test_answer_citations_are_extracted_once_per_breakdown(monkeypatch):
    output = _output()
    ctx = output.context
    id_calls = 0
    result_calls = 0
    original_ids = ctx.cited_result_ids
    original_results = ctx.cited_results

    def counted_ids(answer_text: str):
        nonlocal id_calls
        id_calls += 1
        return original_ids(answer_text)

    def counted_results(answer_text: str):
        nonlocal result_calls
        result_calls += 1
        return original_results(answer_text)

    monkeypatch.setattr(ctx, "cited_result_ids", counted_ids)
    monkeypatch.setattr(ctx, "cited_results", counted_results)

    SearchRewardFunction().reward_components(output, "gold", token_f1_score)

    assert id_calls <= 1
    assert result_calls <= 1


def test_a_fully_zeroed_config_never_traverses_the_search_context(monkeypatch):
    output = _output()

    def forbidden(*args, **kwargs):  # pragma: no cover - must never run
        raise AssertionError("zero-weight config traversed the search context")

    monkeypatch.setattr(output.context, "cited_result_ids", forbidden)
    monkeypatch.setattr(output.context, "cited_results", forbidden)

    reward_fn = SearchRewardFunction(SearchRewardConfig.sparse_final_only())
    components = reward_fn.reward_components(output, "gold", lambda a, g: 0.75)

    assert components["total"] == pytest.approx(0.75)
    assert components["citation_support"] == 0.0
    assert components["fetch_usefulness_reward"] == 0.0


@pytest.mark.parametrize("preset_name", sorted(PRESETS))
@pytest.mark.parametrize("answer", ["Vectors [R1Q1D1] and more [R1Q2D2].", "", None])
def test_every_preset_keeps_its_exact_breakdown(
    preset_name: str, answer: str | None, reward_baseline
):
    reward_fn = SearchRewardFunction(PRESETS[preset_name])

    components = reward_fn.reward_components(_output(answer), "gold", token_f1_score)

    # approx, not ==: the baseline re-derives the breakdown with a different
    # summation order, and only CPython 3.12+ compensates sum() enough to hide
    # the last-ulp gap. The guard is that the numbers do not move, which a
    # tolerance this tight still catches.
    assert components == pytest.approx(reward_baseline(preset_name, answer))


@pytest.mark.parametrize("preset_name", sorted(PRESETS))
def test_every_preset_keeps_its_scalar_total(preset_name: str):
    reward_fn = SearchRewardFunction(PRESETS[preset_name])
    output = _output()

    assert reward_fn.compute(output, "gold", token_f1_score) == pytest.approx(
        reward_fn.reward_components(output, "gold", token_f1_score)["total"]
    )


def test_sparse_token_rewards_land_on_the_last_action_token():
    reward_fn = SearchRewardFunction()
    output = _output()

    vector = reward_fn.compute_sparse_token_rewards(output, "gold", lambda a, g: 1.0)

    assert len(vector) == 8
    assert vector[5] == pytest.approx(reward_fn.config.correctness_weight)
    assert [v for i, v in enumerate(vector) if i != 5] == [0.0] * 7


def test_sparse_token_rewards_fall_back_to_the_last_token_without_a_mask():
    reward_fn = SearchRewardFunction()
    output = _output()
    output.response_mask = [0] * 8

    vector = reward_fn.compute_sparse_token_rewards(output, "gold", lambda a, g: 1.0)

    assert vector[7] == pytest.approx(reward_fn.config.correctness_weight)


def test_token_advantages_and_batch_rewards_share_group_statistics():
    reward_fn = SearchRewardFunction()
    outputs = [_output() for _ in range(4)]
    scores = [1.0, 0.5, 0.0, 0.25]
    judge = dict(zip(range(4), scores))
    seen = iter(scores)

    token_advs = reward_fn.assign_grpo_outcome_token_advantages(
        outputs, ["gold"] * 4, lambda a, g: next(seen), ["x", "x", "y", "y"]
    )

    rewards = [reward_fn.config.correctness_weight * s for s in scores]
    expected = grouped_relative_advantages(
        rewards, ["x", "x", "y", "y"], normalize=True
    )
    assert [row[5] for row in token_advs] == pytest.approx(expected)
    assert judge  # fixture guard: scores consumed in order


# ---------------------------------------------------------------------------
# Context shapes the fast paths must handle identically
# ---------------------------------------------------------------------------


def _output_with(context, answer="Cites [R1Q1D1].", **metric_overrides):
    output = _output(answer)
    output.context = context
    output.metrics.update(metric_overrides)
    return output


@pytest.mark.parametrize("preset_name", sorted(PRESETS))
def test_a_missing_context_produces_the_same_keys_and_no_error(preset_name: str):
    reward_fn = SearchRewardFunction(PRESETS[preset_name])

    with_ctx = reward_fn.reward_components(_output(), "gold", token_f1_score)
    without_ctx = reward_fn.reward_components(
        _output_with(None), "gold", token_f1_score
    )

    assert set(without_ctx) == set(with_ctx)
    assert without_ctx["citation_support"] == 0.0
    assert without_ctx["fetch_usefulness_reward"] == 0.0
    assert without_ctx["unsupported_claim_penalty"] == 0.0


@pytest.mark.parametrize("preset_name", sorted(PRESETS))
def test_an_empty_context_produces_the_same_keys_and_no_error(preset_name: str):
    reward_fn = SearchRewardFunction(PRESETS[preset_name])

    components = reward_fn.reward_components(
        _output_with(AgentContext()), "gold", token_f1_score
    )

    assert set(components) == set(
        reward_fn.reward_components(_output(), "gold", token_f1_score)
    )
    assert components["citation_support"] == 0.0


def test_an_uncited_answer_still_fires_the_unsupported_claim_penalty():
    reward_fn = SearchRewardFunction(SearchRewardConfig.third_pass_with_format())
    assert reward_fn.config.unsupported_claim_penalty != 0.0

    cited = reward_fn.reward_components(_output(), "gold", token_f1_score)
    uncited = reward_fn.reward_components(
        _output("No citations at all here."), "gold", token_f1_score
    )

    assert cited["unsupported_claim_penalty"] == 0.0
    assert uncited["unsupported_claim_penalty"] == pytest.approx(
        reward_fn.config.unsupported_claim_penalty
    )


def test_the_penalty_needs_a_search_to_have_happened():
    reward_fn = SearchRewardFunction(SearchRewardConfig.third_pass_with_format())

    never_searched = reward_fn.reward_components(
        _output_with(_context(), "No citations.", rounds_used=0.0),
        "gold",
        token_f1_score,
    )

    assert never_searched["unsupported_claim_penalty"] == 0.0


def test_fetch_usefulness_needs_the_fetched_url_to_be_cited():
    config = PRESETS["default"]
    reward_fn = SearchRewardFunction(config)
    assert config.fetch_usefulness_reward != 0.0

    ctx = _context()
    ctx.fetched_pages = [SearchResult(contents="p", url="https://unrelated.test/z")]
    unrelated = reward_fn.reward_components(_output_with(ctx), "gold", token_f1_score)
    cited = reward_fn.reward_components(_output(), "gold", token_f1_score)

    assert unrelated["fetch_usefulness_reward"] == 0.0
    assert cited["fetch_usefulness_reward"] == pytest.approx(
        config.fetch_usefulness_reward
    )


def test_zeroed_dimensions_report_every_key_the_full_path_reports():
    full = SearchRewardFunction(SearchRewardConfig()).reward_components(
        _output(), "gold", token_f1_score
    )
    zeroed = SearchRewardFunction(
        SearchRewardConfig.sparse_final_only()
    ).reward_components(_output(), "gold", token_f1_score)

    assert set(zeroed) == set(full)
    assert all(
        isinstance(value, float)
        for key, value in zeroed.items()
        if key != "reward_mode"
    )


@pytest.mark.parametrize(
    ("weight_name", "component_key"),
    [
        ("citation_support_weight", "citation_support"),
        ("unsupported_claim_penalty", "unsupported_claim_penalty"),
        ("fetch_usefulness_reward", "fetch_usefulness_reward"),
        ("format_reward_weight", "format_reward"),
    ],
)
def test_each_citation_term_alone_still_defeats_the_zero_weight_fast_path(
    weight_name: str, component_key: str
):
    """One non-zero weight is enough to require the full citation path.

    No shipped preset enables `fetch_usefulness_reward` on its own, so without
    this case the guard clause for it is never exercised and could be dropped
    without a test noticing.
    """
    config = replace(
        SearchRewardConfig.sparse_final_only(),
        **{weight_name: 0.5 if "penalty" not in weight_name else -0.5},
    )
    answer = "No citations here." if "unsupported" in weight_name else None

    components = SearchRewardFunction(config).reward_components(
        _output(answer) if answer else _output(), "gold", token_f1_score
    )

    assert components[component_key] != 0.0


def _write_baseline() -> None:
    """Capture the current breakdowns as the equivalence baseline."""
    data = {
        preset_name: {
            _answer_key(answer): SearchRewardFunction(config).reward_components(
                _output(answer), "gold", token_f1_score
            )
            for answer in ("Vectors [R1Q1D1] and more [R1Q2D2].", "", None)
        }
        for preset_name, config in PRESETS.items()
    }
    BASELINE_PATH.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    _write_baseline()
    print(f"wrote {BASELINE_PATH}")
